# Generated by Django 4.0.2 on 2022-02-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardsBoard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'boards_board',
                'managed': False,
            },
        ),
    ]
