# Generated by Django 4.0.2 on 2022-02-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsboard',
            options={},
        ),
    ]
